from enum import StrEnum


class ToolStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    PARTIAL = "PARTIAL"
    STALE = "STALE"
    WARMING_UP = "WARMING_UP"
    UNAVAILABLE = "UNAVAILABLE"
    UNAVAILABLE_FOR_INSTRUMENT = "UNAVAILABLE_FOR_INSTRUMENT"
    ERROR = "ERROR"


class Direction(StrEnum):
    LONG_BIAS = "LONG_BIAS"
    SHORT_BIAS = "SHORT_BIAS"


class SignalStrength(StrEnum):
    STRONG = "STRONG"
    WATCH = "WATCH"
    NO_STRONG_SIGNAL = "NO_STRONG_SIGNAL"
    INDETERMINATE = "INDETERMINATE"


class SignalConfidence(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class CycleMode(StrEnum):
    SCHEDULED = "SCHEDULED"
    EMERGENCY = "EMERGENCY"


class CycleStatus(StrEnum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"


class CandidateRiskTag(StrEnum):
    THIN_LIQUIDITY = "THIN_LIQUIDITY"
    CHOPPY = "CHOPPY"
    IMPACT_EXTENDED = "IMPACT_EXTENDED"
    DATA_DEGRADED = "DATA_DEGRADED"


class ThresholdSeverity(StrEnum):
    INFO = "INFO"
    IMPORTANT = "IMPORTANT"
    CRITICAL = "CRITICAL"


class MonitoringReviewDecision(StrEnum):
    ACCEPTED = "ACCEPTED"
    REWRITTEN = "REWRITTEN"
    REJECTED = "REJECTED"


class FailureWorkflow(StrEnum):
    SCHEDULED_ANALYSIS = "SCHEDULED_ANALYSIS"
    EMERGENCY_ANALYSIS = "EMERGENCY_ANALYSIS"
    MONITORING_SETUP = "MONITORING_SETUP"


class FailureStep(StrEnum):
    MARKET_SCAN = "MARKET_SCAN"
    EVIDENCE_COLLECTION = "EVIDENCE_COLLECTION"
    MODEL_ANALYSIS = "MODEL_ANALYSIS"
    FRESHNESS_CHECK = "FRESHNESS_CHECK"
    MONITORING_REVIEW_COLLECTION = "MONITORING_REVIEW_COLLECTION"
    MODEL_MONITORING_REVIEW = "MODEL_MONITORING_REVIEW"
    MECHANICAL_ACTIVATION = "MECHANICAL_ACTIVATION"
    UNKNOWN = "UNKNOWN"


class RetryAction(StrEnum):
    RERUN_SCHEDULED = "RERUN_SCHEDULED"
    RERUN_EMERGENCY = "RERUN_EMERGENCY"
    RERUN_MONITORING = "RERUN_MONITORING"


class RetryStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    INTERRUPTED = "INTERRUPTED"
    SUPERSEDED = "SUPERSEDED"


class FreshnessDecision(StrEnum):
    PASS = "PASS"
    REPAIR = "REPAIR"
    REJECT = "REJECT"


class ToolTurnAction(StrEnum):
    TOOL_REQUESTS = "TOOL_REQUESTS"
    FINAL = "FINAL"


class TrackingStatus(StrEnum):
    NEW = "NEW"
    MAINTAINED = "MAINTAINED"
    REVERSED = "REVERSED"
    EXITED = "EXITED"
    WEAKENED = "WEAKENED"
    INVALIDATED = "INVALIDATED"
    INDETERMINATE = "INDETERMINATE"


class PriceType(StrEnum):
    LAST = "LAST"
    MARK = "MARK"


class MarketType(StrEnum):
    LINEAR_PERPETUAL = "LINEAR_PERPETUAL"
    SPOT = "SPOT"


class Comparator(StrEnum):
    GREATER_THAN = "GREATER_THAN"
    LESS_THAN = "LESS_THAN"


class MonitoringMetric(StrEnum):
    LAST_PRICE = "LAST_PRICE"
    MARK_PRICE = "MARK_PRICE"
    COMPLETED_5M_CLOSE = "COMPLETED_5M_CLOSE"
    COMPLETED_1M_CLOSE = "COMPLETED_1M_CLOSE"
    COMPLETED_15M_CLOSE = "COMPLETED_15M_CLOSE"
    COMPLETED_30M_CLOSE = "COMPLETED_30M_CLOSE"
    COMPLETED_1H_CLOSE = "COMPLETED_1H_CLOSE"
    TURNOVER_1M = "TURNOVER_1M"
    TRADE_DELTA_30S = "TRADE_DELTA_30S"
    CVD_5M = "CVD_5M"
    SPREAD_BPS = "SPREAD_BPS"
    ORDERBOOK_IMBALANCE_L5 = "ORDERBOOK_IMBALANCE_L5"
    OPEN_INTEREST = "OPEN_INTEREST"
    FUNDING_RATE = "FUNDING_RATE"
    LIQUIDATION_NOTIONAL_1M = "LIQUIDATION_NOTIONAL_1M"
