from enum import StrEnum


class ToolStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    PARTIAL = "PARTIAL"
    STALE = "STALE"
    WARMING_UP = "WARMING_UP"
    UNAVAILABLE = "UNAVAILABLE"
    UNAVAILABLE_FOR_INSTRUMENT = "UNAVAILABLE_FOR_INSTRUMENT"
    ERROR = "ERROR"


class Direction(StrEnum):
    LONG_BIAS = "LONG_BIAS"
    SHORT_BIAS = "SHORT_BIAS"


class SignalStrength(StrEnum):
    STRONG = "STRONG"
    WATCH = "WATCH"
    NO_STRONG_SIGNAL = "NO_STRONG_SIGNAL"
    INDETERMINATE = "INDETERMINATE"


class SignalConfidence(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class CycleMode(StrEnum):
    SCHEDULED = "SCHEDULED"
    EMERGENCY = "EMERGENCY"


class CycleStatus(StrEnum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"


class TrackingStatus(StrEnum):
    NEW = "NEW"
    MAINTAINED = "MAINTAINED"
    REVERSED = "REVERSED"
    EXITED = "EXITED"
    WEAKENED = "WEAKENED"
    INVALIDATED = "INVALIDATED"
    INDETERMINATE = "INDETERMINATE"


class PriceType(StrEnum):
    LAST = "LAST"
    MARK = "MARK"


class MarketType(StrEnum):
    LINEAR_PERPETUAL = "LINEAR_PERPETUAL"
    SPOT = "SPOT"


class Comparator(StrEnum):
    GREATER_THAN = "GREATER_THAN"
    LESS_THAN = "LESS_THAN"


class MonitoringMetric(StrEnum):
    LAST_PRICE = "LAST_PRICE"
    MARK_PRICE = "MARK_PRICE"
    COMPLETED_5M_CLOSE = "COMPLETED_5M_CLOSE"
    COMPLETED_15M_CLOSE = "COMPLETED_15M_CLOSE"
    COMPLETED_1H_CLOSE = "COMPLETED_1H_CLOSE"
    TURNOVER_1M = "TURNOVER_1M"
    TRADE_DELTA_30S = "TRADE_DELTA_30S"
    CVD_5M = "CVD_5M"
    SPREAD_BPS = "SPREAD_BPS"
    ORDERBOOK_IMBALANCE_L5 = "ORDERBOOK_IMBALANCE_L5"
    OPEN_INTEREST = "OPEN_INTEREST"
    FUNDING_RATE = "FUNDING_RATE"
    LIQUIDATION_NOTIONAL_1M = "LIQUIDATION_NOTIONAL_1M"
